DROP VIEW `t_bs_area`         ;
CREATE VIEW `t_bs_area`          AS select * from `saasops_manage`.`t_bs_area`         ;
DROP VIEW `t_bs_bank`         ;
CREATE VIEW `t_bs_bank`          AS select * from `saasops_manage`.`t_bs_bank`         ;
DROP VIEW `t_bs_financialcode`;
CREATE VIEW `t_bs_financialcode` AS select * from `saasops_manage`.`t_bs_financialcode`;
DROP VIEW `t_channel_pay`     ;
CREATE VIEW `t_channel_pay`      AS select * from `saasops_manage`.`t_channel_pay`     ;
DROP VIEW `t_cp_company`      ;
CREATE VIEW `t_cp_company`       AS select * from `saasops_manage`.`t_cp_company`      ;
DROP VIEW `t_cp_site`         ;
CREATE VIEW `t_cp_site`          AS select * from `saasops_manage`.`t_cp_site`         ;
DROP VIEW `t_cp_siteurl`      ;
CREATE VIEW `t_cp_siteurl`       AS select * from `saasops_manage`.`t_cp_siteurl`      ;
DROP VIEW `t_game_logo`       ;
CREATE VIEW `t_game_logo`        AS select * from `saasops_manage`.`t_game_logo`       ;
DROP VIEW `t_gm_announcement` ;
CREATE VIEW `t_gm_announcement`  AS select * from `saasops_manage`.`t_gm_announcement` ;
DROP VIEW `t_gm_api`          ;
CREATE VIEW `t_gm_api`           AS select * from `saasops_manage`.`t_gm_api`          ;
DROP VIEW `t_gm_apiprefix`    ;
CREATE VIEW `t_gm_apiprefix`     AS select * from `saasops_manage`.`t_gm_apiprefix`    ;
DROP VIEW `t_gm_cat`          ;
CREATE VIEW `t_gm_cat`           AS select * from `saasops_manage`.`t_gm_cat`          ;
DROP VIEW `t_gm_code`         ;
CREATE VIEW `t_gm_code`          AS select * from `saasops_manage`.`t_gm_code`         ;
DROP VIEW `t_gm_depot`        ;
CREATE VIEW `t_gm_depot`         AS select * from `saasops_manage`.`t_gm_depot`        ;
DROP VIEW `t_gm_depotcat`     ;
CREATE VIEW `t_gm_depotcat`      AS select * from `saasops_manage`.`t_gm_depotcat`     ;
DROP VIEW `t_gm_game`         ;
CREATE VIEW `t_gm_game`          AS select * from `saasops_manage`.`t_gm_game`         ;
DROP VIEW `t_gm_label`        ;
CREATE VIEW `t_gm_label`         AS select * from `saasops_manage`.`t_gm_label`        ;
DROP VIEW `t_i18n`            ;
CREATE VIEW `t_i18n`             AS SELECT * from `saasops_manage`.`t_i18n`            ;
DROP VIEW `t_label_game_depot`;
CREATE VIEW `t_label_game_depot` AS select * from `saasops_manage`.`t_label_game_depot`;
DROP VIEW `t_op_acttmpl`      ;
CREATE VIEW `t_op_acttmpl`       AS select * from `saasops_manage`.`t_op_acttmpl`      ;
DROP VIEW `t_opr_adv`         ;
CREATE VIEW `t_opr_adv`          AS select * from `saasops_manage`.`t_opr_adv`         ;
DROP VIEW `t_opr_notice`      ;
CREATE VIEW `t_opr_notice`       AS select * from `saasops_manage`.`t_opr_notice`      ;
DROP VIEW `t_opt_adv_banner`  ;
CREATE VIEW `t_opt_adv_banner`   AS select * from `saasops_manage`.`t_opt_adv_banner`  ;
DROP VIEW `t_pay`             ;
CREATE VIEW `t_pay`              AS select * from `saasops_manage`.`t_pay`             ;
DROP VIEW `t_pay_bank`        ;
CREATE VIEW `t_pay_bank`         AS select * from `saasops_manage`.`t_pay_bank`        ;
DROP VIEW `t_pay_logo`        ;
CREATE VIEW `t_pay_logo`         AS select * from `saasops_manage`.`t_pay_logo`        ;
DROP VIEW `t_pay_site`        ;
CREATE VIEW `t_pay_site`         AS select * from `saasops_manage`.`t_pay_site`        ;
DROP VIEW `t_restriction`     ;
CREATE VIEW `t_restriction`      AS select * from `saasops_manage`.`t_restriction`     ;
DROP VIEW `t_schema`          ;
CREATE VIEW `t_schema`           AS select * from `saasops_manage`.`t_schema`          ;
DROP VIEW `t_win_top`         ;
CREATE VIEW `t_win_top`          AS select * from `saasops_manage`.`t_win_top`         ;
